config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :subscribers
  resources :categories
  resources :comments
  resources :articles

  root to: "articles#index"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments
  validates :title, :image, presence:true
  has_one_attached :image
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @comment = current_user.comments.build if current_user
  end

  # GET /articles/new
  def new
    @article = current_user.articles.build
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description, :category_id, :image)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="w3-row d-flex justify-content-center">
<div class="w3-col l8 s6">
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div class="alert alert-danger">
      <h5><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h5>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class:"form-control", style:"height:200px;" %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all, :id, :name,{},class: "form-control" %>
  </div>

  <!--<div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>-->

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-success btn-lg" %>
  </div>
<% end %>
</div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center">Edit Article</h1>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<!-- Grid -->
<div class="w3-row">
<!-- Blog entries -->
<div class="w3-col l8 s12">
  <h1 class="pl-4">Articles</h1>
  <% @articles.find_each do |article| %>
  <!-- Blog entry -->
    <div class="w3-card-4 w3-margin w3-white">
      <div class="border">
      <div class="w3-col l8 s7">
        <%= image_tag article.image, width:"100%" %>
      </div>
      <div class="w3-col l4 s5">
        <h4 class="text-center catname"><a href="<%= category_path(article.category.id) %>"><%= article.category.name %> <span> Blogs </span></a></h4>
        <h3 class="w3-padding-large text-uppercase"><b><%= article.title %></b></h3>
        <h5 class="w3-padding-large fs14"><span class="w3-opacity"><%= article.created_at %></span></h5>
      </div>
      </div>

      <div class="w3-container">
        <h5 class="artdesc"><%= article.description %></h5>
        <div class="w3-row">
          <div class="w3-col m8 s12">
            <p><button class="w3-button w3-padding-large w3-white w3-border">
              <b><%= link_to 'READ MORE', article %> &raquo;</b>
            </button></p>
          </div>
          <div class="w3-col m4 w3-hide-small">
            <p><span class="w3-padding-large w3-right"><b>Comments &nbsp;</b> <span class="w3-tag"><%= article.comments.size %></span></span></p>
          </div>
        </div>
      </div>
    </div>
    <hr>
  <!-- END BLOG ENTRIES -->
  <% end %>
  </div>




<!-- Introduction menu -->
<div class="w3-col l4">
  <h1 class="pl-4 mt-5 mt-lg-0">Get To Know More</h1>

  <!-- About Card -->
  <div class="w3-card w3-margin w3-margin-top">
  <%= image_tag "hair.jpg", width:"100%"%>
    <div class="w3-container w3-white">
      <p class="my-4 py-4 bname text-center"><b>Henrietta Osei-Tutu</b></p>
      <p class="fs14">Just me, myself and I, exploring possibilities of better life for all...</p>
    </div>
  </div><hr>


  <!-- Posts -->
  <!-- <div class="w3-card w3-margin">
    <div class="w3-container w3-padding">
      <h4>Popular Posts</h4>
    </div>
    <ul class="w3-ul w3-hoverable w3-white">
      <li class="w3-padding-16">
        <img src="/w3images/workshop.jpg" alt="Image" class="w3-left w3-margin-right" style="width:50px">
        <span class="w3-large">Lorem</span><br>
        <span>Sed mattis nunc</span>
      </li>
      <li class="w3-padding-16">
        <img src="/w3images/gondol.jpg" alt="Image" class="w3-left w3-margin-right" style="width:50px">
        <span class="w3-large">Ipsum</span><br>
        <span>Praes tinci sed</span>
      </li>
      <li class="w3-padding-16">
        <img src="/w3images/skies.jpg" alt="Image" class="w3-left w3-margin-right" style="width:50px">
        <span class="w3-large">Dorum</span><br>
        <span>Ultricies congue</span>
      </li>
      <li class="w3-padding-16 w3-hide-medium w3-hide-small">
        <img src="/w3images/rock.jpg" alt="Image" class="w3-left w3-margin-right" style="width:50px">
        <span class="w3-large">Mingsum</span><br>
        <span>Lorem ipsum dipsum</span>
      </li>
    </ul>
  </div>
  <hr> -->

  <!-- Labels / tags -->
  <!-- <div class="w3-card w3-margin">
    <div class="w3-container w3-padding">
      <h4>Tags</h4>
    </div>
    <div class="w3-container w3-white">
    <p><span class="w3-tag w3-black w3-margin-bottom">Travel</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">New York</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">London</span>
      <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">IKEA</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">NORWAY</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">DIY</span>
      <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Ideas</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Baby</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Family</span>
      <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">News</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Clothing</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Shopping</span>
      <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Sports</span> <span class="w3-tag w3-light-grey w3-small w3-margin-bottom">Games</span>
    </p>
    </div>
  </div> -->

<!-- END Introduction Menu -->
</div>

<!-- END GRID -->
</div><br>

app/views/articles/new.html.erb
<h1 class="text-center">New Article</h1>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<div class="w3-row d-flex justify-content-center">
  <div class="w3-col l10 s8">
    <p class="title m40 text-uppercase">
      <%= @article.title %>
    </p>

    <p class="m40 d-flex w3-card justify-content-center">
      <%= image_tag @article.image %>
    </p>

    <p class="textarea m40 fs16 w3-card bg-white p-5">
      <%= @article.description %>
    </p>

    <div class="m40 w3-container">
      <div class="row d-flex">
        <p class="mr-5 fs14">
          <strong>Category:</strong>
          <%= @article.category.name %>
        </p>

        <p class="fs14 ml-auto">
          <strong>Posted:</strong>
          <%= @article.created_at %>
        </p>
      </div>
    </div>

    <% if @article.user == current_user %>
      <%= link_to 'Edit', edit_article_path(@article), class:"btn btn-warning btn-lg mr-4 m40" %>
    <% end %>

    <div class="mb-5 w3-card w3-padding">
      <h1 class="mb-3" >Comments</h1>
      <ul class="container mb-5">
        <%= render 'comments/list', comment: @comment %>
      </ul>

      <% if user_signed_in? %>
      <div>
      <%= render 'comments/form', comment: @comment %>
      </div>
      <% end %>

    </div>

    <div class="m40">
    <%= link_to 'Back', articles_path, class:"btn btn-primary btn-lg" %>
    </div>

  </div>
</div>