config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :subscribers
  resources :categories
  resources :comments
  resources :articles

  root to: "articles#index"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates  :name, :email, presence:true
  validates_format_of :email, :with => Devise::email_regexp
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_action :set_subscriber, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, except: [:new, :create]

  # GET /subscribers
  # GET /subscribers.json
  def index
    @subscribers = Subscriber.all
  end

  # GET /subscribers/1
  # GET /subscribers/1.json
  def show
  end

  # GET /subscribers/new
  def new
    @subscriber = Subscriber.new
  end

  # GET /subscribers/1/edit
  def edit
  end

  # POST /subscribers
  # POST /subscribers.json
  def create
    @subscriber = Subscriber.new(subscriber_params)

    respond_to do |format|
      if @subscriber.save
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully created.' }
        format.json { render :show, status: :created, location: @subscriber }
      else
        format.html { render :new }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscribers/1
  # PATCH/PUT /subscribers/1.json
  def update
    respond_to do |format|
      if @subscriber.update(subscriber_params)
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscriber }
      else
        format.html { render :edit }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribers/1
  # DELETE /subscribers/1.json
  def destroy
    @subscriber.destroy
    respond_to do |format|
      format.html { redirect_to subscribers_url, notice: 'Subscriber was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscriber
      @subscriber = Subscriber.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subscriber_params
      params.require(:subscriber).permit(:name, :email)
    end
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/subscribers/_form.html.erb
<div class="w3-row d-flex justify-content-center">
<div class="w3-col l8 s6">
<%= form_with(model: subscriber, local: true) do |form| %>
  <% if subscriber.errors.any? %>
    <div class="alert alert-danger">
      <h5><%= pluralize(subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h5>

      <ul>
        <% subscriber.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-success btn-lg" %>
  </div>
<% end %>
</div>
</div>

app/views/subscribers/edit.html.erb
<h1 class="text-center">Editing Subscriber</h1>

<%= render 'form', subscriber: @subscriber %>

<%= link_to 'Show', @subscriber %> |
<%= link_to 'Back', subscribers_path %>

app/views/subscribers/index.html.erb
<h1>Subscribers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscribers.each do |subscriber| %>
      <tr>
        <td><%= subscriber.name %></td>
        <td><%= subscriber.email %></td>
        <td><%= link_to 'Show', subscriber %></td>
        <td><%= link_to 'Edit', edit_subscriber_path(subscriber) %></td>
        <td><%= link_to 'Destroy', subscriber, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscriber', new_subscriber_path %>

app/views/subscribers/new.html.erb
<h1 class="text-center">New Subscriber</h1>

<%= render 'form', subscriber: @subscriber %>

app/views/subscribers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @subscriber.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @subscriber.email %>
</p>

<%= link_to 'Edit', edit_subscriber_path(@subscriber) %> |
<%= link_to 'Back', subscribers_path %>